// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Structura.Web.Persistence;

#nullable disable

namespace Structura.Web.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260711181631_DeliveryFields")]
    partial class DeliveryFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Structura.Web.Domain.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<bool>("IsProtected")
                        .HasColumnType("boolean")
                        .HasColumnName("is_protected");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_app_settings");

                    b.ToTable("app_settings", (string)null);
                });

            modelBuilder.Entity("Structura.Web.Domain.ExtractionResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model");

                    b.Property<string>("Output")
                        .HasColumnType("jsonb")
                        .HasColumnName("output");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<string>("RawResponse")
                        .HasColumnType("text")
                        .HasColumnName("raw_response");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("record_id");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_extraction_results");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_extraction_results_run_id");

                    b.HasIndex("RecordId", "CreatedAt")
                        .HasDatabaseName("ix_extraction_results_record_id_created_at");

                    b.ToTable("extraction_results", null, t =>
                        {
                            t.HasCheckConstraint("ck_extraction_results_status", "status IN ('Succeeded','Failed')");
                        });
                });

            modelBuilder.Entity("Structura.Web.Domain.ImportRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Errors")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("errors");

                    b.Property<int>("Failed")
                        .HasColumnType("integer")
                        .HasColumnName("failed");

                    b.Property<string>("FileName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_path");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<int>("Imported")
                        .HasColumnType("integer")
                        .HasColumnName("imported");

                    b.Property<int>("LastRowProcessed")
                        .HasColumnType("integer")
                        .HasColumnName("last_row_processed");

                    b.Property<string>("Mapping")
                        .HasColumnType("jsonb")
                        .HasColumnName("mapping");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("SkippedDuplicates")
                        .HasColumnType("integer")
                        .HasColumnName("skipped_duplicates");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<int?>("TotalRows")
                        .HasColumnType("integer")
                        .HasColumnName("total_rows");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_import_runs");

                    b.HasIndex("ProjectId", "CreatedAt")
                        .HasDatabaseName("ix_import_runs_project_id_created_at");

                    b.ToTable("import_runs", null, t =>
                        {
                            t.HasCheckConstraint("ck_import_runs_source", "source IN ('Excel','Csv','Manual','Api')");

                            t.HasCheckConstraint("ck_import_runs_status", "status IN ('AwaitingMapping','Running','Completed','CompletedWithErrors','Failed','Cancelled')");
                        });
                });

            modelBuilder.Entity("Structura.Web.Domain.ProcessingRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("CancelRequested")
                        .HasColumnType("boolean")
                        .HasColumnName("cancel_requested");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<int>("Failed")
                        .HasColumnType("integer")
                        .HasColumnName("failed");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<long>("InputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("input_tokens");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("output_tokens");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("PromptSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("prompt_snapshot");

                    b.Property<string>("SchemaSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("schema_snapshot");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<int>("Succeeded")
                        .HasColumnType("integer")
                        .HasColumnName("succeeded");

                    b.Property<int>("Total")
                        .HasColumnType("integer")
                        .HasColumnName("total");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_processing_runs");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_processing_runs_status")
                        .HasFilter("status = 'Running'");

                    b.HasIndex("ProjectId", "CreatedAt")
                        .HasDatabaseName("ix_processing_runs_project_id_created_at");

                    b.ToTable("processing_runs", null, t =>
                        {
                            t.HasCheckConstraint("ck_processing_runs_status", "status IN ('Running','Completed','CompletedWithErrors','Cancelled','Failed')");
                        });
                });

            modelBuilder.Entity("Structura.Web.Domain.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AiConfig")
                        .HasColumnType("jsonb")
                        .HasColumnName("ai_config");

                    b.Property<string>("ApiInputConfig")
                        .HasColumnType("jsonb")
                        .HasColumnName("api_input_config");

                    b.Property<string>("ApiOutputConfig")
                        .HasColumnType("jsonb")
                        .HasColumnName("api_output_config");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PromptConfig")
                        .HasColumnType("jsonb")
                        .HasColumnName("prompt_config");

                    b.Property<string>("SchemaFields")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("schema_fields");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_projects_created_by_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_projects_name");

                    b.ToTable("projects", null, t =>
                        {
                            t.HasCheckConstraint("ck_projects_status", "status IN ('Active','Archived')");
                        });
                });

            modelBuilder.Entity("Structura.Web.Domain.ProjectMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_project_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_project_members_user_id");

                    b.HasIndex("ProjectId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_project_members_project_id_user_id");

                    b.ToTable("project_members", (string)null);
                });

            modelBuilder.Entity("Structura.Web.Domain.Record", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid?>("AssignedReviewerId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_reviewer_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<int>("DeliveryAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("delivery_attempts");

                    b.Property<string>("DeliveryError")
                        .HasColumnType("text")
                        .HasColumnName("delivery_error");

                    b.Property<string>("DeliveryExternalId")
                        .HasColumnType("text")
                        .HasColumnName("delivery_external_id");

                    b.Property<DateTimeOffset?>("DeliveryNextRetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivery_next_retry_at");

                    b.Property<string>("DeliveryStatusValue")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("delivery_status");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("external_id");

                    b.Property<string>("FinalOutput")
                        .HasColumnType("jsonb")
                        .HasColumnName("final_output");

                    b.Property<Guid?>("ImportRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("import_run_id");

                    b.Property<Guid?>("LatestResultId")
                        .HasColumnType("uuid")
                        .HasColumnName("latest_result_id");

                    b.Property<string>("ProcessingError")
                        .HasColumnType("text")
                        .HasColumnName("processing_error");

                    b.Property<Guid?>("ProcessingRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("processing_run_id");

                    b.Property<string>("ProcessingStatusValue")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("processing_status");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text")
                        .HasColumnName("review_note");

                    b.Property<string>("ReviewStatusValue")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("review_status");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedById")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_records");

                    b.HasIndex("AssignedReviewerId")
                        .HasDatabaseName("ix_records_assigned_reviewer_id");

                    b.HasIndex("ImportRunId")
                        .HasDatabaseName("ix_records_import_run_id");

                    b.HasIndex("ReviewedById")
                        .HasDatabaseName("ix_records_reviewed_by_id");

                    b.HasIndex("ProcessingRunId", "ProcessingStatusValue")
                        .HasDatabaseName("ix_records_processing_run_id_processing_status");

                    b.HasIndex("ProjectId", "DeliveryStatusValue")
                        .HasDatabaseName("ix_records_project_id_delivery_status");

                    b.HasIndex("ProjectId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_records_project_id_external_id");

                    b.HasIndex("ProjectId", "ProcessingStatusValue")
                        .HasDatabaseName("ix_records_project_id_processing_status");

                    b.HasIndex("ProjectId", "ReviewStatusValue")
                        .HasDatabaseName("ix_records_project_id_review_status");

                    b.HasIndex("ProjectId", "UpdatedAt")
                        .HasDatabaseName("ix_records_project_id_updated_at");

                    b.HasIndex("ProjectId", "AssignedReviewerId", "ReviewStatusValue")
                        .HasDatabaseName("ix_records_project_id_assigned_reviewer_id_review_status");

                    b.HasIndex("ProjectId", "ReviewStatusValue", "DeliveryStatusValue")
                        .HasDatabaseName("ix_records_project_id_review_status_delivery_status");

                    b.ToTable("records", null, t =>
                        {
                            t.HasCheckConstraint("ck_records_delivery_status", "delivery_status IN ('Pending','Delivered','Failed')");

                            t.HasCheckConstraint("ck_records_processing_status", "processing_status IN ('Pending','Processing','Completed','Failed')");

                            t.HasCheckConstraint("ck_records_review_status", "review_status IN ('Unassigned','Assigned','InReview','Approved','Rejected','ReprocessRequested')");
                        });
                });

            modelBuilder.Entity("Structura.Web.Domain.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("ReplacedById")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Structura.Web.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_count");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTimeOffset?>("LockoutEndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end_at");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean")
                        .HasColumnName("must_change_password");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("role");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("security_stamp");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_role", "role IN ('Administrator','ProjectManager','Reviewer')");
                        });
                });

            modelBuilder.Entity("Structura.Web.Domain.ExtractionResult", b =>
                {
                    b.HasOne("Structura.Web.Domain.Record", "Record")
                        .WithMany()
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_extraction_results_records_record_id");

                    b.HasOne("Structura.Web.Domain.ProcessingRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_extraction_results_processing_runs_run_id");

                    b.Navigation("Record");
                });

            modelBuilder.Entity("Structura.Web.Domain.ImportRun", b =>
                {
                    b.HasOne("Structura.Web.Domain.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_import_runs_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Structura.Web.Domain.ProcessingRun", b =>
                {
                    b.HasOne("Structura.Web.Domain.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_processing_runs_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Structura.Web.Domain.Project", b =>
                {
                    b.HasOne("Structura.Web.Domain.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_projects_users_created_by_id");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Structura.Web.Domain.ProjectMember", b =>
                {
                    b.HasOne("Structura.Web.Domain.Project", "Project")
                        .WithMany("Members")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_members_projects_project_id");

                    b.HasOne("Structura.Web.Domain.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_members_users_user_id");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Structura.Web.Domain.Record", b =>
                {
                    b.HasOne("Structura.Web.Domain.User", "AssignedReviewer")
                        .WithMany()
                        .HasForeignKey("AssignedReviewerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_records_users_assigned_reviewer_id");

                    b.HasOne("Structura.Web.Domain.ImportRun", null)
                        .WithMany()
                        .HasForeignKey("ImportRunId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_records_import_runs_import_run_id");

                    b.HasOne("Structura.Web.Domain.ProcessingRun", null)
                        .WithMany()
                        .HasForeignKey("ProcessingRunId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_records_processing_runs_processing_run_id");

                    b.HasOne("Structura.Web.Domain.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_records_projects_project_id");

                    b.HasOne("Structura.Web.Domain.User", "ReviewedBy")
                        .WithMany()
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_records_users_reviewed_by_id");

                    b.Navigation("AssignedReviewer");

                    b.Navigation("Project");

                    b.Navigation("ReviewedBy");
                });

            modelBuilder.Entity("Structura.Web.Domain.RefreshToken", b =>
                {
                    b.HasOne("Structura.Web.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Structura.Web.Domain.Project", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Structura.Web.Domain.User", b =>
                {
                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
